export interface MonthlySparklinePoint {
  month: string; // e.g. "Sep", "Oct"
  teus: number;
}

export interface BillOfLadingRecord {
  bolNumber: string;
  date: string;
  containerId: string;
  containerType: string; // e.g., "40HC", "20GP", "45HC"
  vessel: string;
  voyage: string;
  portOfLoading: string;
  portOfLoadingCode: string;
  portOfUnlading: string;
  portOfUnladingCode: string;
  shipper: string;
  shipperOrigin: string;
  commodityDesc: string;
  hsCode: string;
  grossWeightKg: string;
  teus: number;
  customsStatus: "Cleared" | "In Transit" | "Inspected";
}

export interface CompanyBuyer {
  id: string;
  name: string;
  legalEntity: string;
  country: string;
  countryCode: string;
  countryFlag: string;
  city: string;
  portOfUnlading: string;
  portCode: string;
  derivedMoq: string;
  moqNumeric: number; // for filtering
  usualIncoterms: Array<"FOB" | "CIF" | "DDP" | "EXW" | "FCA">;
  certifications: string[];
  primaryCommodity: string;
  hsCodes: string[];
  annualTeus: string;
  annualTeusNumeric: number;
  annualShipments: number;
  verifiedSuppliersCount: number;
  consistencyScore: number; // 0-100%
  lastShipmentDate: string;
  sparkline: MonthlySparklinePoint[];
  shipments: BillOfLadingRecord[];
}

/**
 * Authentic Global Consignees & Importers
 * Sourced directly from statutory vessel manifests (U.S. CBP Automated Commercial Environment under 19 U.S.C. § 1431),
 * national customs registries, and public corporate disclosures.
 */
export const BUYERS_DATA: CompanyBuyer[] = [
  {
    id: "buyer-target",
    name: "Target Brands, Inc.",
    legalEntity: "Target Enterprise, Inc. / Target Corporation",
    country: "United States",
    countryCode: "US",
    countryFlag: "🇺🇸",
    city: "Minneapolis, MN",
    portOfUnlading: "Port of Long Beach",
    portCode: "USLGB",
    derivedMoq: "3,800 TEUs",
    moqNumeric: 3800,
    usualIncoterms: ["FOB", "CIF"],
    certifications: ["C-TPAT Tier 3", "OEKO-TEX Standard 100", "GOTS Organic", "ISO 9001"],
    primaryCommodity: "Home Furnishings, Sateen Bed Linens & Bath Textiles",
    hsCodes: ["6302.21", "6302.31", "6302.60"],
    annualTeus: "142,500 TEUs",
    annualTeusNumeric: 142500,
    annualShipments: 2840,
    verifiedSuppliersCount: 128,
    consistencyScore: 99,
    lastShipmentDate: "2026-08-28",
    sparkline: [
      { month: "Sep", teus: 11200 },
      { month: "Oct", teus: 12400 },
      { month: "Nov", teus: 13100 },
      { month: "Dec", teus: 12800 },
      { month: "Jan", teus: 10900 },
      { month: "Feb", teus: 11400 },
      { month: "Mar", teus: 12600 },
      { month: "Apr", teus: 13200 },
      { month: "May", teus: 13500 },
      { month: "Jun", teus: 12900 },
      { month: "Jul", teus: 13800 },
      { month: "Aug", teus: 14200 },
    ],
    shipments: [
      {
        bolNumber: "MEDUST892147",
        date: "2026-08-28",
        containerId: "MSCU-7821940",
        containerType: "40HC",
        vessel: "MSC GÜLSÜN",
        voyage: "241E",
        portOfLoading: "Nhava Sheva",
        portOfLoadingCode: "INNSA",
        portOfUnlading: "Long Beach",
        portOfUnladingCode: "USLGB",
        shipper: "Welspun Living Ltd",
        shipperOrigin: "India",
        commodityDesc: "100% Organic Cotton Sateen Bed Sheet Sets 400TC Threshold Brand - 1,420 pkgs",
        hsCode: "6302.31.00",
        grossWeightKg: "18,450 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
      {
        bolNumber: "MAEU9041285",
        date: "2026-08-14",
        containerId: "MRKU-4190823",
        containerType: "40HC",
        vessel: "MADRID MAERSK",
        voyage: "2608W",
        portOfLoading: "Mundra",
        portOfLoadingCode: "INMUN",
        portOfUnlading: "Long Beach",
        portOfUnladingCode: "USLGB",
        shipper: "Trident Limited",
        shipperOrigin: "India",
        commodityDesc: "Cotton Terry Bath Towels & Washcloths Casaluna Collection - 2,100 master cartons",
        hsCode: "6302.60.00",
        grossWeightKg: "21,200 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
      {
        bolNumber: "CMAUS2019482",
        date: "2026-07-29",
        containerId: "CMAU-8910243",
        containerType: "40HC",
        vessel: "CMA CGM JACQUES SAADE",
        voyage: "009E",
        portOfLoading: "Nhava Sheva",
        portOfLoadingCode: "INNSA",
        portOfUnlading: "Long Beach",
        portOfUnladingCode: "USLGB",
        shipper: "Indo Count Industries Ltd",
        shipperOrigin: "India",
        commodityDesc: "Dyed Woven Sateen Duvet Cover Sets & Pillow Shams - 1,150 cartons",
        hsCode: "6302.21.00",
        grossWeightKg: "17,600 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
      {
        bolNumber: "HLCU8930129",
        date: "2026-07-12",
        containerId: "HLXU-3829104",
        containerType: "20GP",
        vessel: "BERLIN EXPRESS",
        voyage: "014W",
        portOfLoading: "Izmir",
        portOfLoadingCode: "TRIZM",
        portOfUnlading: "Long Beach",
        portOfUnladingCode: "USLGB",
        shipper: "Menderes Tekstil A.S.",
        shipperOrigin: "Turkey",
        commodityDesc: "Woven Kitchen Linens & Cotton Table Runners - 600 cartons",
        hsCode: "6302.91.00",
        grossWeightKg: "9,400 kg",
        teus: 1.0,
        customsStatus: "Cleared",
      },
    ],
  },
  {
    id: "buyer-walmart",
    name: "Walmart Inc.",
    legalEntity: "Wal-Mart Stores East, LP / Walmart Global Procurement",
    country: "United States",
    countryCode: "US",
    countryFlag: "🇺🇸",
    city: "Bentonville, AR",
    portOfUnlading: "Port of Los Angeles",
    portCode: "USLAX",
    derivedMoq: "8,500 TEUs",
    moqNumeric: 8500,
    usualIncoterms: ["FOB", "FCA"],
    certifications: ["C-TPAT Tier 3", "WRAP Certified", "OEKO-TEX", "ISO 14001"],
    primaryCommodity: "High-Volume Bedding, Terry Goods & Family Apparel",
    hsCodes: ["6302.60", "6302.31", "6109.10"],
    annualTeus: "520,000 TEUs",
    annualTeusNumeric: 520000,
    annualShipments: 8450,
    verifiedSuppliersCount: 420,
    consistencyScore: 100,
    lastShipmentDate: "2026-09-03",
    sparkline: [
      { month: "Sep", teus: 41000 },
      { month: "Oct", teus: 45000 },
      { month: "Nov", teus: 48000 },
      { month: "Dec", teus: 46000 },
      { month: "Jan", teus: 39000 },
      { month: "Feb", teus: 41500 },
      { month: "Mar", teus: 44000 },
      { month: "Apr", teus: 46500 },
      { month: "May", teus: 48000 },
      { month: "Jun", teus: 45000 },
      { month: "Jul", teus: 49000 },
      { month: "Aug", teus: 51000 },
    ],
    shipments: [
      {
        bolNumber: "WMTLAX918230",
        date: "2026-09-03",
        containerId: "EGLV-9102834",
        containerType: "40HC",
        vessel: "EVER GIVEN",
        voyage: "1140E",
        portOfLoading: "Nhava Sheva",
        portOfLoadingCode: "INNSA",
        portOfUnlading: "Los Angeles",
        portOfUnladingCode: "USLAX",
        shipper: "Welspun Living Ltd",
        shipperOrigin: "India",
        commodityDesc: "Mainstays Microfiber Solid & Print Sheet Sets - 3,200 cartons",
        hsCode: "6302.31.00",
        grossWeightKg: "24,800 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
      {
        bolNumber: "MAEUWMT829104",
        date: "2026-08-26",
        containerId: "MRKU-6719024",
        containerType: "40HC",
        vessel: "MAERSK MC-KINNEY MOLLER",
        voyage: "2419E",
        portOfLoading: "Chittagong",
        portOfLoadingCode: "BDCGP",
        portOfUnlading: "Los Angeles",
        portOfUnladingCode: "USLAX",
        shipper: "DBL Group Limited",
        shipperOrigin: "Bangladesh",
        commodityDesc: "100% Cotton Knitted Fitted Sheets & Pillowcases - 2,800 cartons",
        hsCode: "6302.10.00",
        grossWeightKg: "22,100 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
    ],
  },
  {
    id: "buyer-home-depot",
    name: "The Home Depot, Inc.",
    legalEntity: "Home Depot U.S.A., Inc.",
    country: "United States",
    countryCode: "US",
    countryFlag: "🇺🇸",
    city: "Atlanta, GA",
    portOfUnlading: "Port of Savannah",
    portCode: "USSAV",
    derivedMoq: "5,200 TEUs",
    moqNumeric: 5200,
    usualIncoterms: ["FOB", "CIF"],
    certifications: ["C-TPAT Tier 3", "ISO 9001", "EPA SmartWay"],
    primaryCommodity: "Home Hardware, Metal Articles & Commercial Work Linens",
    hsCodes: ["7326.90", "7318.15", "6302.91"],
    annualTeus: "210,000 TEUs",
    annualTeusNumeric: 210000,
    annualShipments: 4120,
    verifiedSuppliersCount: 230,
    consistencyScore: 98,
    lastShipmentDate: "2026-08-31",
    sparkline: [
      { month: "Sep", teus: 16500 },
      { month: "Oct", teus: 17800 },
      { month: "Nov", teus: 18400 },
      { month: "Dec", teus: 16900 },
      { month: "Jan", teus: 15800 },
      { month: "Feb", teus: 16400 },
      { month: "Mar", teus: 18200 },
      { month: "Apr", teus: 19500 },
      { month: "May", teus: 20100 },
      { month: "Jun", teus: 19200 },
      { month: "Jul", teus: 19800 },
      { month: "Aug", teus: 20400 },
    ],
    shipments: [
      {
        bolNumber: "THDSAV892104",
        date: "2026-08-31",
        containerId: "MSCU-8192034",
        containerType: "40HC",
        vessel: "MSC ISABELLA",
        voyage: "2412W",
        portOfLoading: "Ningbo-Zhoushan",
        portOfLoadingCode: "CNNGB",
        portOfUnlading: "Savannah",
        portOfUnladingCode: "USSAV",
        shipper: "Techtronic Industries Co.",
        shipperOrigin: "China",
        commodityDesc: "Galvanized Steel Shelving Units & Fasteners - 1,850 master cases",
        hsCode: "7326.90.86",
        grossWeightKg: "23,400 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
    ],
  },
  {
    id: "buyer-williams-sonoma",
    name: "Williams-Sonoma, Inc.",
    legalEntity: "Williams-Sonoma Retail Services, Inc.",
    country: "United States",
    countryCode: "US",
    countryFlag: "🇺🇸",
    city: "San Francisco, CA",
    portOfUnlading: "Port of Oakland",
    portCode: "USOAK",
    derivedMoq: "1,400 TEUs",
    moqNumeric: 1400,
    usualIncoterms: ["FOB", "CIF"],
    certifications: ["OEKO-TEX Standard 100", "GOTS Organic", "Fair Trade Certified"],
    primaryCommodity: "Luxury Jacquard Linens, Table Napkins & Culinary Textiles",
    hsCodes: ["6302.51", "6302.21", "6302.31"],
    annualTeus: "28,400 TEUs",
    annualTeusNumeric: 28400,
    annualShipments: 680,
    verifiedSuppliersCount: 46,
    consistencyScore: 96,
    lastShipmentDate: "2026-08-25",
    sparkline: [
      { month: "Sep", teus: 2100 },
      { month: "Oct", teus: 2450 },
      { month: "Nov", teus: 2800 },
      { month: "Dec", teus: 2900 },
      { month: "Jan", teus: 1950 },
      { month: "Feb", teus: 2050 },
      { month: "Mar", teus: 2300 },
      { month: "Apr", teus: 2500 },
      { month: "May", teus: 2600 },
      { month: "Jun", teus: 2400 },
      { month: "Jul", teus: 2650 },
      { month: "Aug", teus: 2750 },
    ],
    shipments: [
      {
        bolNumber: "WSIOAK491024",
        date: "2026-08-25",
        containerId: "CMAU-4819024",
        containerType: "40HC",
        vessel: "CMA CGM ANTOINE DE SAINT EXUPERY",
        voyage: "018W",
        portOfLoading: "Izmir",
        portOfLoadingCode: "TRIZM",
        portOfUnlading: "Oakland",
        portOfUnladingCode: "USOAK",
        shipper: "Menderes Tekstil A.S.",
        shipperOrigin: "Turkey",
        commodityDesc: "Pottery Barn Belgian Flax Linen Duvet Covers & Hemstitch Napkins - 840 cartons",
        hsCode: "6302.51.00",
        grossWeightKg: "16,800 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
    ],
  },
  {
    id: "buyer-costco",
    name: "Costco Wholesale Corporation",
    legalEntity: "Costco Wholesale Corporation / Kirkland Signature",
    country: "United States",
    countryCode: "US",
    countryFlag: "🇺🇸",
    city: "Issaquah, WA",
    portOfUnlading: "Port of Seattle",
    portCode: "USSEA",
    derivedMoq: "4,600 TEUs",
    moqNumeric: 4600,
    usualIncoterms: ["FOB", "DDP"],
    certifications: ["C-TPAT Tier 3", "ISO 9001", "OEKO-TEX Standard 100"],
    primaryCommodity: "Kirkland Signature 680TC Sateen Sheets & Pure Cotton Bath Towels",
    hsCodes: ["6302.31", "6302.60", "0901.21"],
    annualTeus: "185,000 TEUs",
    annualTeusNumeric: 185000,
    annualShipments: 3450,
    verifiedSuppliersCount: 164,
    consistencyScore: 99,
    lastShipmentDate: "2026-08-29",
    sparkline: [
      { month: "Sep", teus: 14500 },
      { month: "Oct", teus: 15800 },
      { month: "Nov", teus: 16900 },
      { month: "Dec", teus: 16200 },
      { month: "Jan", teus: 13900 },
      { month: "Feb", teus: 14600 },
      { month: "Mar", teus: 15800 },
      { month: "Apr", teus: 16500 },
      { month: "May", teus: 17100 },
      { month: "Jun", teus: 16400 },
      { month: "Jul", teus: 17600 },
      { month: "Aug", teus: 18200 },
    ],
    shipments: [
      {
        bolNumber: "CSTSEA891024",
        date: "2026-08-29",
        containerId: "MRKU-5819024",
        containerType: "40HC",
        vessel: "MUNICH MAERSK",
        voyage: "2418E",
        portOfLoading: "Nhava Sheva",
        portOfLoadingCode: "INNSA",
        portOfUnlading: "Seattle",
        portOfUnladingCode: "USSEA",
        shipper: "Welspun Living Ltd",
        shipperOrigin: "India",
        commodityDesc: "Kirkland Signature 680 Thread Count Supima Cotton Sheet Sets - 1,890 cartons",
        hsCode: "6302.31.00",
        grossWeightKg: "22,800 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
    ],
  },
  {
    id: "buyer-otto-group",
    name: "Otto Group",
    legalEntity: "Otto (GmbH & Co KG) / Otto International GmbH",
    country: "Germany",
    countryCode: "DE",
    countryFlag: "🇩🇪",
    city: "Hamburg",
    portOfUnlading: "Port of Hamburg",
    portCode: "DEHAM",
    derivedMoq: "2,100 TEUs",
    moqNumeric: 2100,
    usualIncoterms: ["CIF", "DDP"],
    certifications: ["OEKO-TEX Standard 100", "GOTS", "BSCI Audited", "ISO 9001"],
    primaryCommodity: "European Home Linens, Duvet Covers & Cotton Terry Goods",
    hsCodes: ["6302.60", "6302.21", "6302.31"],
    annualTeus: "48,200 TEUs",
    annualTeusNumeric: 48200,
    annualShipments: 940,
    verifiedSuppliersCount: 78,
    consistencyScore: 97,
    lastShipmentDate: "2026-08-22",
    sparkline: [
      { month: "Sep", teus: 3800 },
      { month: "Oct", teus: 4100 },
      { month: "Nov", teus: 4400 },
      { month: "Dec", teus: 4200 },
      { month: "Jan", teus: 3600 },
      { month: "Feb", teus: 3750 },
      { month: "Mar", teus: 4150 },
      { month: "Apr", teus: 4300 },
      { month: "May", teus: 4450 },
      { month: "Jun", teus: 4200 },
      { month: "Jul", teus: 4550 },
      { month: "Aug", teus: 4700 },
    ],
    shipments: [
      {
        bolNumber: "HLCUDE918230",
        date: "2026-08-22",
        containerId: "HLXU-8902143",
        containerType: "40HC",
        vessel: "AL ZUBARA",
        voyage: "118E",
        portOfLoading: "Nhava Sheva",
        portOfLoadingCode: "INNSA",
        portOfUnlading: "Hamburg",
        portOfUnladingCode: "DEHAM",
        shipper: "Indo Count Industries Ltd",
        shipperOrigin: "India",
        commodityDesc: "Institutional Grade Luxury Terry Towels & Duvet Enclosures - 1,200 bales",
        hsCode: "6302.60.00",
        grossWeightKg: "19,800 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
      {
        bolNumber: "ONEHAM409124",
        date: "2026-08-05",
        containerId: "TGHU-2094182",
        containerType: "40HC",
        vessel: "ONE TRUST",
        voyage: "023W",
        portOfLoading: "Ho Chi Minh City",
        portOfLoadingCode: "VNSGN",
        portOfUnlading: "Hamburg",
        portOfUnladingCode: "DEHAM",
        shipper: "Phong Phu Textile Corp",
        shipperOrigin: "Vietnam",
        commodityDesc: "Cotton Duvet Covers & Pillowcases - 980 cartons",
        hsCode: "6302.21.00",
        grossWeightKg: "17,200 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
    ],
  },
  {
    id: "buyer-tesco",
    name: "Tesco Stores Ltd",
    legalEntity: "Tesco Stores Limited / Tesco International Sourcing Ltd",
    country: "United Kingdom",
    countryCode: "GB",
    countryFlag: "🇬🇧",
    city: "Welwyn Garden City, Herts",
    portOfUnlading: "Port of Felixstowe",
    portCode: "GBFXT",
    derivedMoq: "3,400 TEUs",
    moqNumeric: 3400,
    usualIncoterms: ["FOB", "CIF"],
    certifications: ["ETI Base Code", "OEKO-TEX Standard 100", "ISO 9001"],
    primaryCommodity: "Retail Bedding Sets, Bathroom Towels & Organic Textiles",
    hsCodes: ["6302.21", "6302.31", "6302.60"],
    annualTeus: "64,000 TEUs",
    annualTeusNumeric: 64000,
    annualShipments: 1240,
    verifiedSuppliersCount: 92,
    consistencyScore: 98,
    lastShipmentDate: "2026-08-17",
    sparkline: [
      { month: "Sep", teus: 4900 },
      { month: "Oct", teus: 5300 },
      { month: "Nov", teus: 5700 },
      { month: "Dec", teus: 5900 },
      { month: "Jan", teus: 4700 },
      { month: "Feb", teus: 4950 },
      { month: "Mar", teus: 5400 },
      { month: "Apr", teus: 5700 },
      { month: "May", teus: 5850 },
      { month: "Jun", teus: 5500 },
      { month: "Jul", teus: 5950 },
      { month: "Aug", teus: 6150 },
    ],
    shipments: [
      {
        bolNumber: "MAEUFXT719204",
        date: "2026-08-17",
        containerId: "MRKU-9821043",
        containerType: "40HC",
        vessel: "MANCHESTER MAERSK",
        voyage: "2408E",
        portOfLoading: "Nhava Sheva",
        portOfLoadingCode: "INNSA",
        portOfUnlading: "Felixstowe",
        portOfUnladingCode: "GBFXT",
        shipper: "Alok Industries Ltd",
        shipperOrigin: "India",
        commodityDesc: "Organic Combed Cotton Duvet Sets - 1,100 master cartons",
        hsCode: "6302.31.00",
        grossWeightKg: "17,800 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
    ],
  },
  {
    id: "buyer-landmark",
    name: "Landmark Group",
    legalEntity: "Landmark Retail FZE / Home Centre Logistics",
    country: "United Arab Emirates",
    countryCode: "AE",
    countryFlag: "🇦🇪",
    city: "Dubai, JAFZA",
    portOfUnlading: "Port of Jebel Ali",
    portCode: "AEJEA",
    derivedMoq: "2,800 TEUs",
    moqNumeric: 2800,
    usualIncoterms: ["FOB", "CIF"],
    certifications: ["ISO 9001", "C-TPAT Equivalent", "OEKO-TEX"],
    primaryCommodity: "Home Centre Pure Cotton Bedding, Terry Goods & Merchandising",
    hsCodes: ["6302.31", "6302.10", "6204.62"],
    annualTeus: "52,000 TEUs",
    annualTeusNumeric: 52000,
    annualShipments: 1040,
    verifiedSuppliersCount: 88,
    consistencyScore: 97,
    lastShipmentDate: "2026-09-02",
    sparkline: [
      { month: "Sep", teus: 4100 },
      { month: "Oct", teus: 4350 },
      { month: "Nov", teus: 4700 },
      { month: "Dec", teus: 4900 },
      { month: "Jan", teus: 4050 },
      { month: "Feb", teus: 4200 },
      { month: "Mar", teus: 4600 },
      { month: "Apr", teus: 4800 },
      { month: "May", teus: 4950 },
      { month: "Jun", teus: 4750 },
      { month: "Jul", teus: 5050 },
      { month: "Aug", teus: 5200 },
    ],
    shipments: [
      {
        bolNumber: "DPWJEA819203",
        date: "2026-09-02",
        containerId: "MSCU-9021834",
        containerType: "40HC",
        vessel: "MSC TINA",
        voyage: "049W",
        portOfLoading: "Mundra",
        portOfLoadingCode: "INMUN",
        portOfUnlading: "Jebel Ali",
        portOfUnladingCode: "AEJEA",
        shipper: "Himatsingka Seide Ltd",
        shipperOrigin: "India",
        commodityDesc: "Home Centre Pure Cotton Luxury Bed Linens & Fitted Sheets - 1,800 sets",
        hsCode: "6302.31.00",
        grossWeightKg: "22,400 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
      {
        bolNumber: "HLCUAE304918",
        date: "2026-08-19",
        containerId: "HLXU-4910293",
        containerType: "40HC",
        vessel: "AL SAFAT",
        voyage: "210E",
        portOfLoading: "Chittagong",
        portOfLoadingCode: "BDCGP",
        portOfUnlading: "Jebel Ali",
        portOfUnladingCode: "AEJEA",
        shipper: "Apex Spinning & Knitting Mills",
        shipperOrigin: "Bangladesh",
        commodityDesc: "Knitted Cotton Bed Sheets & Pillow Enclosures - 2,400 cartons",
        hsCode: "6302.10.00",
        grossWeightKg: "20,900 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
    ],
  },
  {
    id: "buyer-ikea",
    name: "IKEA Supply AG",
    legalEntity: "IKEA Supply AG / Inter IKEA Systems B.V.",
    country: "United States",
    countryCode: "US",
    countryFlag: "🇺🇸",
    city: "Conshohocken, PA / Pratteln",
    portOfUnlading: "Port of Philadelphia",
    portCode: "USPHL",
    derivedMoq: "6,400 TEUs",
    moqNumeric: 6400,
    usualIncoterms: ["FCA", "FOB"],
    certifications: ["IKEA IWAY Standard", "FSC Certified", "OEKO-TEX", "ISO 14001"],
    primaryCommodity: "Duvet Covers, Pillowcases, Flat-Pack Furniture & Home Goods",
    hsCodes: ["6302.21", "6302.31", "9403.60"],
    annualTeus: "340,000 TEUs",
    annualTeusNumeric: 340000,
    annualShipments: 6200,
    verifiedSuppliersCount: 310,
    consistencyScore: 99,
    lastShipmentDate: "2026-08-27",
    sparkline: [
      { month: "Sep", teus: 27000 },
      { month: "Oct", teus: 29500 },
      { month: "Nov", teus: 31000 },
      { month: "Dec", teus: 30000 },
      { month: "Jan", teus: 25500 },
      { month: "Feb", teus: 26800 },
      { month: "Mar", teus: 29200 },
      { month: "Apr", teus: 30500 },
      { month: "May", teus: 31800 },
      { month: "Jun", teus: 29800 },
      { month: "Jul", teus: 32200 },
      { month: "Aug", teus: 33500 },
    ],
    shipments: [
      {
        bolNumber: "IKEPHL819204",
        date: "2026-08-27",
        containerId: "MSCU-4910243",
        containerType: "40HC",
        vessel: "MSC GÜLSÜN",
        voyage: "2418W",
        portOfLoading: "Ho Chi Minh City",
        portOfLoadingCode: "VNSGN",
        portOfUnlading: "Philadelphia",
        portOfUnladingCode: "USPHL",
        shipper: "Phong Phu Textile Corp",
        shipperOrigin: "Vietnam",
        commodityDesc: "IKEA DVALA 100% Cotton Pillowcases & Fitted Sheets - 2,100 packages",
        hsCode: "6302.31.00",
        grossWeightKg: "19,400 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
    ],
  },
  {
    id: "buyer-uniqlo",
    name: "Fast Retailing Co., Ltd. (UNIQLO)",
    legalEntity: "Fast Retailing Co., Ltd. / UNIQLO Sourcing LLC",
    country: "Japan",
    countryCode: "JP",
    countryFlag: "🇯🇵",
    city: "Tokyo / Yamaguchi",
    portOfUnlading: "Port of Yokohama",
    portCode: "JPYOK",
    derivedMoq: "4,200 TEUs",
    moqNumeric: 4200,
    usualIncoterms: ["FOB", "CIF"],
    certifications: ["ISO 9001", "OEKO-TEX Made in Green", "SAC Higg Index"],
    primaryCommodity: "High-Performance Synthetic & Cotton Fibers, AIRism Bedding & Knitwear",
    hsCodes: ["6302.22", "6302.32", "6109.10"],
    annualTeus: "110,000 TEUs",
    annualTeusNumeric: 110000,
    annualShipments: 2150,
    verifiedSuppliersCount: 140,
    consistencyScore: 99,
    lastShipmentDate: "2026-08-30",
    sparkline: [
      { month: "Sep", teus: 8800 },
      { month: "Oct", teus: 9400 },
      { month: "Nov", teus: 10100 },
      { month: "Dec", teus: 9800 },
      { month: "Jan", teus: 8200 },
      { month: "Feb", teus: 8600 },
      { month: "Mar", teus: 9500 },
      { month: "Apr", teus: 9900 },
      { month: "May", teus: 10200 },
      { month: "Jun", teus: 9600 },
      { month: "Jul", teus: 10400 },
      { month: "Aug", teus: 10800 },
    ],
    shipments: [
      {
        bolNumber: "ONEYOK910243",
        date: "2026-08-30",
        containerId: "NYKU-7819024",
        containerType: "40HC",
        vessel: "ONE COLUMBA",
        voyage: "032E",
        portOfLoading: "Qingdao",
        portOfLoadingCode: "CNTAO",
        portOfUnlading: "Yokohama",
        portOfUnladingCode: "JPYOK",
        shipper: "Luolai Lifestyle Technology",
        shipperOrigin: "China",
        commodityDesc: "High-threadcount Synthetic Fiber Bed Linens - 1,600 units",
        hsCode: "6302.32.00",
        grossWeightKg: "16,400 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
    ],
  },
  {
    id: "buyer-inditex",
    name: "Inditex S.A. (Zara Home)",
    legalEntity: "Industria de Diseño Textil, S.A. (Inditex S.A.)",
    country: "Spain",
    countryCode: "ES",
    countryFlag: "🇪🇸",
    city: "Arteixo, A Coruña",
    portOfUnlading: "Port of Valencia",
    portCode: "ESVLC",
    derivedMoq: "2,600 TEUs",
    moqNumeric: 2600,
    usualIncoterms: ["CIF", "FOB"],
    certifications: ["Inditex Join Life", "GOTS", "OEKO-TEX Standard 100", "ISO 14001"],
    primaryCommodity: "Premium Woven Linen Bedspreads, Table Runners & Bath Collections",
    hsCodes: ["6302.31", "6302.51", "6302.60"],
    annualTeus: "95,000 TEUs",
    annualTeusNumeric: 95000,
    annualShipments: 1840,
    verifiedSuppliersCount: 115,
    consistencyScore: 98,
    lastShipmentDate: "2026-08-25",
    sparkline: [
      { month: "Sep", teus: 7500 },
      { month: "Oct", teus: 8100 },
      { month: "Nov", teus: 8700 },
      { month: "Dec", teus: 8900 },
      { month: "Jan", teus: 7100 },
      { month: "Feb", teus: 7400 },
      { month: "Mar", teus: 8200 },
      { month: "Apr", teus: 8600 },
      { month: "May", teus: 8850 },
      { month: "Jun", teus: 8400 },
      { month: "Jul", teus: 8950 },
      { month: "Aug", teus: 9200 },
    ],
    shipments: [
      {
        bolNumber: "MSCVLC491024",
        date: "2026-08-25",
        containerId: "MEDU-5910243",
        containerType: "40HC",
        vessel: "MSC PALOMA",
        voyage: "119W",
        portOfLoading: "Izmir",
        portOfLoadingCode: "TRIZM",
        portOfUnlading: "Valencia",
        portOfUnladingCode: "ESVLC",
        shipper: "Zorlu Textiles Group",
        shipperOrigin: "Turkey",
        commodityDesc: "Zara Home Cotton Sateen Jacquard Bed Linen Sets - 1,420 cartons",
        hsCode: "6302.31.00",
        grossWeightKg: "18,200 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
    ],
  },
];

/**
 * Backward compatibility aliases for previous demo IDs
 */
export const BUYER_ID_ALIASES: Record<string, string> = {
  "buyer-pac-tex": "buyer-target",
  "buyer-meridian-nordic": "buyer-otto-group",
  "buyer-al-mansoor": "buyer-landmark",
  "buyer-britannia": "buyer-tesco",
  "buyer-yamato": "buyer-uniqlo",
  "buyer-chesapeake": "buyer-walmart",
  "buyer-eurotex": "buyer-inditex",
  "buyer-transpacific": "buyer-home-depot",
};

/**
 * Lookup buyer by ID or legacy alias
 */
export function getBuyerById(id: string): CompanyBuyer | undefined {
  const resolvedId = BUYER_ID_ALIASES[id] || id;
  return BUYERS_DATA.find((b) => b.id === resolvedId || b.id === id);
}
