export interface MonthlySparklinePoint {
  month: string; // e.g. "Sep", "Oct"
  teus: number;
}

export interface BillOfLadingRecord {
  bolNumber: string;
  date: string;
  containerId: string;
  containerType: string; // e.g., "40HC", "20GP", "45HC"
  vessel: string;
  voyage: string;
  portOfLoading: string;
  portOfLoadingCode: string;
  portOfUnlading: string;
  portOfUnladingCode: string;
  shipper: string;
  shipperOrigin: string;
  commodityDesc: string;
  hsCode: string;
  grossWeightKg: string;
  teus: number;
  customsStatus: "Cleared" | "In Transit" | "Inspected";
}

export interface CompanyBuyer {
  id: string;
  name: string;
  legalEntity: string;
  country: string;
  countryCode: string;
  countryFlag: string;
  city: string;
  portOfUnlading: string;
  portCode: string;
  derivedMoq: string;
  moqNumeric: number; // for filtering
  usualIncoterms: Array<"FOB" | "CIF" | "DDP" | "EXW" | "FCA">;
  certifications: string[];
  primaryCommodity: string;
  hsCodes: string[];
  annualTeus: string;
  annualTeusNumeric: number;
  annualShipments: number;
  verifiedSuppliersCount: number;
  consistencyScore: number; // 0-100%
  lastShipmentDate: string;
  sparkline: MonthlySparklinePoint[];
  shipments: BillOfLadingRecord[];
}

export const BUYERS_DATA: CompanyBuyer[] = [
  {
    id: "buyer-pac-tex",
    name: "Pacific Textiles LLC",
    legalEntity: "Pacific Textiles Import Corporation",
    country: "United States",
    countryCode: "US",
    countryFlag: "🇺🇸",
    city: "Los Angeles, CA",
    portOfUnlading: "Port of Long Beach",
    portCode: "USLGB",
    derivedMoq: "1,200 TEUs",
    moqNumeric: 1200,
    usualIncoterms: ["FOB", "CIF"],
    certifications: ["OEKO-TEX", "GOTS", "ISO 9001"],
    primaryCommodity: "Home Furnishings & Bed Linens",
    hsCodes: ["6302.21", "6302.31", "6304.92"],
    annualTeus: "4,850 TEUs",
    annualTeusNumeric: 4850,
    annualShipments: 142,
    verifiedSuppliersCount: 18,
    consistencyScore: 94,
    lastShipmentDate: "2026-08-28",
    sparkline: [
      { month: "Sep", teus: 380 },
      { month: "Oct", teus: 410 },
      { month: "Nov", teus: 430 },
      { month: "Dec", teus: 390 },
      { month: "Jan", teus: 360 },
      { month: "Feb", teus: 375 },
      { month: "Mar", teus: 420 },
      { month: "Apr", teus: 440 },
      { month: "May", teus: 450 },
      { month: "Jun", teus: 435 },
      { month: "Jul", teus: 460 },
      { month: "Aug", teus: 470 },
    ],
    shipments: [
      {
        bolNumber: "MEDUST892147",
        date: "2026-08-28",
        containerId: "MSCU-7821940",
        containerType: "40HC",
        vessel: "MSC GÜLSÜN",
        voyage: "241E",
        portOfLoading: "Nhava Sheva",
        portOfLoadingCode: "INNSA",
        portOfUnlading: "Long Beach",
        portOfUnladingCode: "USLGB",
        shipper: "Welspun Living Ltd",
        shipperOrigin: "India",
        commodityDesc: "100% Organic Cotton Sateen Bed Sheet Sets 400TC - 1,420 pkgs",
        hsCode: "6302.31.00",
        grossWeightKg: "18,450 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
      {
        bolNumber: "MAEU9041285",
        date: "2026-08-14",
        containerId: "MRKU-4190823",
        containerType: "40HC",
        vessel: "MADRID MAERSK",
        voyage: "2608W",
        portOfLoading: "Mundra",
        portOfLoadingCode: "INMUN",
        portOfUnlading: "Long Beach",
        portOfUnladingCode: "USLGB",
        shipper: "Trident Textiles Global",
        shipperOrigin: "India",
        commodityDesc: "Cotton Terry Bath Towels & Washcloths - 2,100 master cartons",
        hsCode: "6302.60.00",
        grossWeightKg: "21,200 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
      {
        bolNumber: "CMAUS2019482",
        date: "2026-07-29",
        containerId: "CMAU-8910243",
        containerType: "40HC",
        vessel: "CMA CGM JACQUES SAADE",
        voyage: "009E",
        portOfLoading: "Karachi",
        portOfLoadingCode: "PKKHI",
        portOfUnlading: "Long Beach",
        portOfUnladingCode: "USLGB",
        shipper: "Indus Home Textiles Ltd",
        shipperOrigin: "Pakistan",
        commodityDesc: "Dyed Woven Table Linens & Napkin Sets - 850 cartons",
        hsCode: "6302.51.00",
        grossWeightKg: "16,800 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
      {
        bolNumber: "HLCU8930129",
        date: "2026-07-12",
        containerId: "HLXU-3829104",
        containerType: "20GP",
        vessel: "BERLIN EXPRESS",
        voyage: "014W",
        portOfLoading: "Izmir",
        portOfLoadingCode: "TRIZM",
        portOfUnlading: "Long Beach",
        portOfUnladingCode: "USLGB",
        shipper: "Menderes Tekstil A.S.",
        shipperOrigin: "Turkey",
        commodityDesc: "Woven Kitchen Linens & Cotton Aprons - 600 cartons",
        hsCode: "6302.91.00",
        grossWeightKg: "9,400 kg",
        teus: 1.0,
        customsStatus: "Cleared",
      },
    ],
  },
  {
    id: "buyer-meridian-nordic",
    name: "Meridian Nordic Distribution AG",
    legalEntity: "Meridian Nordic Handel & Logistik AG",
    country: "Germany",
    countryCode: "DE",
    countryFlag: "🇩🇪",
    city: "Hamburg",
    portOfUnlading: "Port of Hamburg",
    portCode: "DEHAM",
    derivedMoq: "850 TEUs",
    moqNumeric: 850,
    usualIncoterms: ["CIF", "DDP"],
    certifications: ["ISO 9001", "OEKO-TEX"],
    primaryCommodity: "Hospitality Textiles & Terry Goods",
    hsCodes: ["6302.60", "6302.91"],
    annualTeus: "2,940 TEUs",
    annualTeusNumeric: 2940,
    annualShipments: 98,
    verifiedSuppliersCount: 12,
    consistencyScore: 91,
    lastShipmentDate: "2026-08-22",
    sparkline: [
      { month: "Sep", teus: 230 },
      { month: "Oct", teus: 250 },
      { month: "Nov", teus: 260 },
      { month: "Dec", teus: 240 },
      { month: "Jan", teus: 210 },
      { month: "Feb", teus: 225 },
      { month: "Mar", teus: 255 },
      { month: "Apr", teus: 270 },
      { month: "May", teus: 265 },
      { month: "Jun", teus: 250 },
      { month: "Jul", teus: 275 },
      { month: "Aug", teus: 280 },
    ],
    shipments: [
      {
        bolNumber: "HLCUDE918230",
        date: "2026-08-22",
        containerId: "HLXU-8902143",
        containerType: "40HC",
        vessel: "AL ZUBARA",
        voyage: "118E",
        portOfLoading: "Nhava Sheva",
        portOfLoadingCode: "INNSA",
        portOfUnlading: "Hamburg",
        portOfUnladingCode: "DEHAM",
        shipper: "Indo Count Industries Ltd",
        shipperOrigin: "India",
        commodityDesc: "Institutional Grade White Terry Towels for Hotels - 1,200 bales",
        hsCode: "6302.60.00",
        grossWeightKg: "19,800 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
      {
        bolNumber: "ONEHAM409124",
        date: "2026-08-05",
        containerId: "TGHU-2094182",
        containerType: "40HC",
        vessel: "ONE TRUST",
        voyage: "023W",
        portOfLoading: "Ho Chi Minh City",
        portOfLoadingCode: "VNSGN",
        portOfUnlading: "Hamburg",
        portOfUnladingCode: "DEHAM",
        shipper: "Phong Phu Textile Corp",
        shipperOrigin: "Vietnam",
        commodityDesc: "Cotton Duvet Covers & Pillowcases - 980 cartons",
        hsCode: "6302.21.00",
        grossWeightKg: "17,200 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
    ],
  },
  {
    id: "buyer-al-mansoor",
    name: "Al-Mansoor Gulf Logistics FZE",
    legalEntity: "Al-Mansoor General Trading & Logistics FZE",
    country: "United Arab Emirates",
    countryCode: "AE",
    countryFlag: "🇦🇪",
    city: "Dubai, JAFZA",
    portOfUnlading: "Port of Jebel Ali",
    portCode: "AEJEA",
    derivedMoq: "2,400 TEUs",
    moqNumeric: 2400,
    usualIncoterms: ["FOB", "EXW"],
    certifications: ["ISO 9001", "C-TPAT"],
    primaryCommodity: "High-Volume Commodity Linens & Apparel",
    hsCodes: ["6302.10", "6302.31", "6204.62"],
    annualTeus: "7,820 TEUs",
    annualTeusNumeric: 7820,
    annualShipments: 210,
    verifiedSuppliersCount: 34,
    consistencyScore: 97,
    lastShipmentDate: "2026-09-02",
    sparkline: [
      { month: "Sep", teus: 590 },
      { month: "Oct", teus: 630 },
      { month: "Nov", teus: 680 },
      { month: "Dec", teus: 720 },
      { month: "Jan", teus: 610 },
      { month: "Feb", teus: 640 },
      { month: "Mar", teus: 690 },
      { month: "Apr", teus: 710 },
      { month: "May", teus: 730 },
      { month: "Jun", teus: 700 },
      { month: "Jul", teus: 740 },
      { month: "Aug", teus: 760 },
    ],
    shipments: [
      {
        bolNumber: "DPWJEA819203",
        date: "2026-09-02",
        containerId: "MSCU-9021834",
        containerType: "40HC",
        vessel: "MSC TINA",
        voyage: "049W",
        portOfLoading: "Mundra",
        portOfLoadingCode: "INMUN",
        portOfUnlading: "Jebel Ali",
        portOfUnladingCode: "AEJEA",
        shipper: "Himatsingka Seide Ltd",
        shipperOrigin: "India",
        commodityDesc: "Pure Cotton Luxury Bed Linens & Fitted Sheets - 1,800 sets",
        hsCode: "6302.31.00",
        grossWeightKg: "22,400 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
      {
        bolNumber: "HLCUAE304918",
        date: "2026-08-19",
        containerId: "HLXU-4910293",
        containerType: "40HC",
        vessel: "AL SAFAT",
        voyage: "210E",
        portOfLoading: "Chittagong",
        portOfLoadingCode: "BDCGP",
        portOfUnlading: "Jebel Ali",
        portOfUnladingCode: "AEJEA",
        shipper: "Apex Spinning & Knitting Mills",
        shipperOrigin: "Bangladesh",
        commodityDesc: "Knitted Cotton Bed Sheets & Pillow Enclosures - 2,400 cartons",
        hsCode: "6302.10.00",
        grossWeightKg: "20,900 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
    ],
  },
  {
    id: "buyer-britannia",
    name: "Britannia Home Furnishings Ltd",
    legalEntity: "Britannia Home Retail Holdings Ltd",
    country: "United Kingdom",
    countryCode: "GB",
    countryFlag: "🇬🇧",
    city: "London / Manchester",
    portOfUnlading: "Port of Felixstowe",
    portCode: "GBFXT",
    derivedMoq: "450 TEUs",
    moqNumeric: 450,
    usualIncoterms: ["FOB", "CIF"],
    certifications: ["OEKO-TEX", "GOTS"],
    primaryCommodity: "Sustainable & Organic Textiles",
    hsCodes: ["6302.21", "6302.31"],
    annualTeus: "1,820 TEUs",
    annualTeusNumeric: 1820,
    annualShipments: 64,
    verifiedSuppliersCount: 9,
    consistencyScore: 89,
    lastShipmentDate: "2026-08-17",
    sparkline: [
      { month: "Sep", teus: 140 },
      { month: "Oct", teus: 155 },
      { month: "Nov", teus: 165 },
      { month: "Dec", teus: 170 },
      { month: "Jan", teus: 130 },
      { month: "Feb", teus: 135 },
      { month: "Mar", teus: 160 },
      { month: "Apr", teus: 175 },
      { month: "May", teus: 165 },
      { month: "Jun", teus: 150 },
      { month: "Jul", teus: 170 },
      { month: "Aug", teus: 180 },
    ],
    shipments: [
      {
        bolNumber: "MAEUFXT719204",
        date: "2026-08-17",
        containerId: "MRKU-9821043",
        containerType: "40HC",
        vessel: "MANCHESTER MAERSK",
        voyage: "2408E",
        portOfLoading: "Nhava Sheva",
        portOfLoadingCode: "INNSA",
        portOfUnlading: "Felixstowe",
        portOfUnladingCode: "GBFXT",
        shipper: "Alok Industries Ltd",
        shipperOrigin: "India",
        commodityDesc: "Organic Combed Cotton Duvet Sets - 1,100 master cartons",
        hsCode: "6302.31.00",
        grossWeightKg: "17,800 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
    ],
  },
  {
    id: "buyer-yamato",
    name: "Yamato Global Supply Corp",
    legalEntity: "Yamato Trading & Procurement Kabushiki Kaisha",
    country: "Japan",
    countryCode: "JP",
    countryFlag: "🇯🇵",
    city: "Tokyo / Yokohama",
    portOfUnlading: "Port of Yokohama",
    portCode: "JPYOK",
    derivedMoq: "1,800 TEUs",
    moqNumeric: 1800,
    usualIncoterms: ["CIF", "FCA"],
    certifications: ["ISO 9001", "C-TPAT"],
    primaryCommodity: "Precision Fiber & Institutional Linens",
    hsCodes: ["6302.22", "6302.32", "8471.50"],
    annualTeus: "5,400 TEUs",
    annualTeusNumeric: 5400,
    annualShipments: 128,
    verifiedSuppliersCount: 22,
    consistencyScore: 98,
    lastShipmentDate: "2026-08-30",
    sparkline: [
      { month: "Sep", teus: 420 },
      { month: "Oct", teus: 440 },
      { month: "Nov", teus: 460 },
      { month: "Dec", teus: 450 },
      { month: "Jan", teus: 410 },
      { month: "Feb", teus: 430 },
      { month: "Mar", teus: 470 },
      { month: "Apr", teus: 485 },
      { month: "May", teus: 490 },
      { month: "Jun", teus: 475 },
      { month: "Jul", teus: 500 },
      { month: "Aug", teus: 510 },
    ],
    shipments: [
      {
        bolNumber: "ONEYOK910243",
        date: "2026-08-30",
        containerId: "NYKU-7819024",
        containerType: "40HC",
        vessel: "ONE COLUMBA",
        voyage: "032E",
        portOfLoading: "Qingdao",
        portOfLoadingCode: "CNTAO",
        portOfUnlading: "Yokohama",
        portOfUnladingCode: "JPYOK",
        shipper: "Luolai Lifestyle Technology",
        shipperOrigin: "China",
        commodityDesc: "High-threadcount Synthetic Fiber Bed Linens - 1,600 units",
        hsCode: "6302.32.00",
        grossWeightKg: "16,400 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
    ],
  },
  {
    id: "buyer-chesapeake",
    name: "Chesapeake Retail Partners",
    legalEntity: "Chesapeake Merchandising Group LLC",
    country: "United States",
    countryCode: "US",
    countryFlag: "🇺🇸",
    city: "Newark, NJ",
    portOfUnlading: "Port of New York / New Jersey",
    portCode: "USNYC",
    derivedMoq: "3,200 TEUs",
    moqNumeric: 3200,
    usualIncoterms: ["FOB", "DDP"],
    certifications: ["C-TPAT", "ISO 9001", "OEKO-TEX"],
    primaryCommodity: "Department Store Bedding & Bath Linens",
    hsCodes: ["6302.21", "6302.60"],
    annualTeus: "9,640 TEUs",
    annualTeusNumeric: 9640,
    annualShipments: 284,
    verifiedSuppliersCount: 42,
    consistencyScore: 96,
    lastShipmentDate: "2026-09-01",
    sparkline: [
      { month: "Sep", teus: 760 },
      { month: "Oct", teus: 810 },
      { month: "Nov", teus: 840 },
      { month: "Dec", teus: 820 },
      { month: "Jan", teus: 740 },
      { month: "Feb", teus: 780 },
      { month: "Mar", teus: 830 },
      { month: "Apr", teus: 870 },
      { month: "May", teus: 890 },
      { month: "Jun", teus: 860 },
      { month: "Jul", teus: 910 },
      { month: "Aug", teus: 930 },
    ],
    shipments: [
      {
        bolNumber: "MSCNYC781290",
        date: "2026-09-01",
        containerId: "MSCU-6712904",
        containerType: "40HC",
        vessel: "MSC AMELIA",
        voyage: "2418W",
        portOfLoading: "Nhava Sheva",
        portOfLoadingCode: "INNSA",
        portOfUnlading: "Newark",
        portOfUnladingCode: "USNYC",
        shipper: "Welspun Living Ltd",
        shipperOrigin: "India",
        commodityDesc: "Cotton Flannel Bedding Sets & Fitted Sheets - 1,840 pkgs",
        hsCode: "6302.21.00",
        grossWeightKg: "21,800 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
    ],
  },
  {
    id: "buyer-eurotex",
    name: "Eurotex Fashion SpA",
    legalEntity: "Eurotex Distribuzione Tessile SpA",
    country: "Italy",
    countryCode: "IT",
    countryFlag: "🇮🇹",
    city: "Milan / Genoa",
    portOfUnlading: "Port of Genoa",
    portCode: "ITGOA",
    derivedMoq: "650 TEUs",
    moqNumeric: 650,
    usualIncoterms: ["CIF", "FOB"],
    certifications: ["OEKO-TEX", "GOTS", "ISO 9001"],
    primaryCommodity: "Premium Sateen Bedding & Table Runners",
    hsCodes: ["6302.31", "6302.51"],
    annualTeus: "2,150 TEUs",
    annualTeusNumeric: 2150,
    annualShipments: 72,
    verifiedSuppliersCount: 14,
    consistencyScore: 92,
    lastShipmentDate: "2026-08-25",
    sparkline: [
      { month: "Sep", teus: 170 },
      { month: "Oct", teus: 185 },
      { month: "Nov", teus: 195 },
      { month: "Dec", teus: 190 },
      { month: "Jan", teus: 160 },
      { month: "Feb", teus: 165 },
      { month: "Mar", teus: 180 },
      { month: "Apr", teus: 195 },
      { month: "May", teus: 200 },
      { month: "Jun", teus: 190 },
      { month: "Jul", teus: 205 },
      { month: "Aug", teus: 215 },
    ],
    shipments: [
      {
        bolNumber: "MSCITG491024",
        date: "2026-08-25",
        containerId: "MEDU-5910243",
        containerType: "40HC",
        vessel: "MSC PALOMA",
        voyage: "119W",
        portOfLoading: "Izmir",
        portOfLoadingCode: "TRIZM",
        portOfUnlading: "Genoa",
        portOfUnladingCode: "ITGOA",
        shipper: "Zorlu Textiles Group",
        shipperOrigin: "Turkey",
        commodityDesc: "Cotton Sateen Jacquard Bed Linen Sets - 720 cartons",
        hsCode: "6302.31.00",
        grossWeightKg: "15,200 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
    ],
  },
  {
    id: "buyer-transpacific",
    name: "Trans-Pacific Consumer Brands Inc",
    legalEntity: "Trans-Pacific Import & Retail Group Inc",
    country: "United States",
    countryCode: "US",
    countryFlag: "🇺🇸",
    city: "Atlanta, GA",
    portOfUnlading: "Port of Savannah",
    portCode: "USSAV",
    derivedMoq: "1,600 TEUs",
    moqNumeric: 1600,
    usualIncoterms: ["FOB", "FCA"],
    certifications: ["FDA Registered", "C-TPAT", "ISO 9001"],
    primaryCommodity: "Healthcare Bed Linens & Institutional Robes",
    hsCodes: ["6302.21", "6302.91"],
    annualTeus: "5,120 TEUs",
    annualTeusNumeric: 5120,
    annualShipments: 164,
    verifiedSuppliersCount: 20,
    consistencyScore: 95,
    lastShipmentDate: "2026-08-27",
    sparkline: [
      { month: "Sep", teus: 410 },
      { month: "Oct", teus: 430 },
      { month: "Nov", teus: 450 },
      { month: "Dec", teus: 430 },
      { month: "Jan", teus: 390 },
      { month: "Feb", teus: 410 },
      { month: "Mar", teus: 445 },
      { month: "Apr", teus: 460 },
      { month: "May", teus: 475 },
      { month: "Jun", teus: 455 },
      { month: "Jul", teus: 480 },
      { month: "Aug", teus: 495 },
    ],
    shipments: [
      {
        bolNumber: "MAEUUSS819204",
        date: "2026-08-27",
        containerId: "MRKU-1029482",
        containerType: "40HC",
        vessel: "MAERSK MC-KINNEY MOLLER",
        voyage: "2419E",
        portOfLoading: "Nhava Sheva",
        portOfLoadingCode: "INNSA",
        portOfUnlading: "Savannah",
        portOfUnladingCode: "USSAV",
        shipper: "Himatsingka Seide Ltd",
        shipperOrigin: "India",
        commodityDesc: "Hospital Grade Antimicrobial Fitted Bed Sheets - 1,600 master cases",
        hsCode: "6302.21.00",
        grossWeightKg: "19,500 kg",
        teus: 2.0,
        customsStatus: "Cleared",
      },
    ],
  },
];
