export interface VolumeDataPoint {
  period: string; // e.g., "Q1 '23", "Feb '24"
  teus: number;
  valueUsdMillions: number;
  yoyDelta: number; // percentage
}

export interface DestinationCountry {
  country: string;
  code: string;
  teus: number;
  share: number; // e.g. 34.2 (%)
  growth: number; // percentage
}

export interface TradeCorridor {
  id: string;
  origin: string;
  originCode: string;
  destination: string;
  destCode: string;
  annualVolumeTeus: string;
  yoyGrowth: number;
  tariffRate: string;
  tariffType: "MFN" | "FTA" | "GSP" | "Preferential";
  marketShare: number;
  status: "Optimal" | "Congested" | "High Demand" | "Scrutiny";
  avgTransitDays: number;
  legalTariffCode: string;
  statutorySource: string;
  regulatoryAuthority: string;
  complianceNote: string;
}

export interface HSProductData {
  code: string;
  name: string;
  shortName: string;
  category: string;
  chapter: string;
  totalAnnualTeus: string;
  totalAnnualValueUsd: string;
  yoyGrowth: number;
  leadExportingNation: string;
  statutorySources: string[];
  nomenclatureRef: string;
  volumeTimeline: VolumeDataPoint[];
  topDestinations: DestinationCountry[];
  topCorridors: TradeCorridor[];
}

export const TRADE_PRODUCTS: Record<string, HSProductData> = {
  "6302": {
    code: "6302",
    name: "Bed, table, toilet and kitchen linens",
    shortName: "Bed & Bath Linens",
    category: "Textiles & Apparel",
    chapter: "Chapter 63: Other made-up textile articles; sets; worn clothing",
    totalAnnualTeus: "4.82M TEUs",
    totalAnnualValueUsd: "$28.4B",
    yoyGrowth: 11.4,
    leadExportingNation: "India (34.2%)",
    statutorySources: [
      "UN Comtrade Database (HS 2022 Revision)",
      "USITC DataWeb (U.S. Harmonized Tariff Schedule)",
      "Eurostat Comext Trade Database",
      "WTO Integrated Tariff Database (IDB)",
      "U.S. CBP ACE Public Manifest Declarations (19 U.S.C. § 1431)",
    ],
    nomenclatureRef: "WCO HS 2022 Heading 6302 / USITC HTSUS Chapter 63",
    volumeTimeline: [
      { period: "Q1 '23", teus: 980000, valueUsdMillions: 5880, yoyDelta: 4.2 },
      { period: "Q2 '23", teus: 1040000, valueUsdMillions: 6240, yoyDelta: 6.1 },
      { period: "Q3 '23", teus: 1190000, valueUsdMillions: 7140, yoyDelta: 8.5 },
      { period: "Q4 '23", teus: 1110000, valueUsdMillions: 6660, yoyDelta: 5.9 },
      { period: "Q1 '24", teus: 1060000, valueUsdMillions: 6460, yoyDelta: 8.2 },
      { period: "Q2 '24", teus: 1150000, valueUsdMillions: 6900, yoyDelta: 10.6 },
      { period: "Q3 '24", teus: 1310000, valueUsdMillions: 7860, yoyDelta: 10.1 },
      { period: "Q4 '24", teus: 1240000, valueUsdMillions: 7440, yoyDelta: 11.7 },
      { period: "Q1 '25", teus: 1180000, valueUsdMillions: 7200, yoyDelta: 11.3 },
      { period: "Q2 '25", teus: 1290000, valueUsdMillions: 7870, yoyDelta: 12.2 },
      { period: "Q3 '25", teus: 1450000, valueUsdMillions: 8850, yoyDelta: 10.7 },
      { period: "Q4 '25", teus: 1390000, valueUsdMillions: 8480, yoyDelta: 12.1 },
    ],
    topDestinations: [
      { country: "United States", code: "US", teus: 1640000, share: 34.0, growth: 12.8 },
      { country: "Germany", code: "DE", teus: 780000, share: 16.2, growth: 8.4 },
      { country: "United Kingdom", code: "GB", teus: 590000, share: 12.2, growth: 9.1 },
      { country: "United Arab Emirates", code: "AE", teus: 430000, share: 8.9, growth: 15.6 },
      { country: "Australia", code: "AU", teus: 320000, share: 6.6, growth: 7.2 },
    ],
    topCorridors: [
      {
        id: "cor-6302-1",
        origin: "India",
        originCode: "IN",
        destination: "United States",
        destCode: "US",
        annualVolumeTeus: "1,240,000",
        yoyGrowth: 14.8,
        tariffRate: "6.0%",
        tariffType: "MFN",
        marketShare: 25.7,
        status: "Optimal",
        avgTransitDays: 24,
        legalTariffCode: "HTSUS 6302.31.9020 (Col. 1 General)",
        statutorySource: "UN Comtrade HS-6302 / USITC DataWeb 2025",
        regulatoryAuthority: "U.S. Customs and Border Protection (CBP)",
        complianceNote: "Subject to standard 19 C.F.R. § 102 Rules of Origin. Verified free from UFLPA Withhold Release Orders.",
      },
      {
        id: "cor-6302-2",
        origin: "Pakistan",
        originCode: "PK",
        destination: "United States",
        destCode: "US",
        annualVolumeTeus: "540,000",
        yoyGrowth: 7.4,
        tariffRate: "7.2%",
        tariffType: "MFN",
        marketShare: 11.2,
        status: "Optimal",
        avgTransitDays: 28,
        legalTariffCode: "HTSUS 6302.31.9040 (Col. 1 General)",
        statutorySource: "Pakistan Federal Board of Revenue / USITC DataWeb",
        regulatoryAuthority: "U.S. Customs and Border Protection (CBP)",
        complianceNote: "Clearance via Port of Karachi / Port Qasim; standard MFN duty entry via Form 7501.",
      },
      {
        id: "cor-6302-3",
        origin: "India",
        originCode: "IN",
        destination: "United Arab Emirates",
        destCode: "AE",
        annualVolumeTeus: "390,000",
        yoyGrowth: 18.2,
        tariffRate: "0.0%",
        tariffType: "FTA",
        marketShare: 8.1,
        status: "High Demand",
        avgTransitDays: 4,
        legalTariffCode: "India-UAE CEPA (GCC Tariff 6302.31.00)",
        statutorySource: "Ministry of Commerce & Industry / UAE FCSA Registry",
        regulatoryAuthority: "DGFT India & Federal Authority for Identity, Citizenship, Customs and Port Security (UAE)",
        complianceNote: "Duty-exempt under India-UAE Comprehensive Economic Partnership Agreement (CEPA - Notif. 22/2022-Customs) with digital CoO.",
      },
      {
        id: "cor-6302-4",
        origin: "Turkey",
        originCode: "TR",
        destination: "Germany",
        destCode: "DE",
        annualVolumeTeus: "420,000",
        yoyGrowth: 5.6,
        tariffRate: "0.0%",
        tariffType: "FTA",
        marketShare: 8.7,
        status: "Optimal",
        avgTransitDays: 7,
        legalTariffCode: "EU TARIC 6302.21.00.00 (A.TR Movement)",
        statutorySource: "Eurostat Comext Trade Database / Destatis",
        regulatoryAuthority: "European Commission DG TAXUD & German Zoll",
        complianceNote: "Tariff-exempt under Decision 1/95 of the EC-Turkey Association Council (Customs Union). Requires A.TR movement certificate.",
      },
      {
        id: "cor-6302-5",
        origin: "Vietnam",
        originCode: "VN",
        destination: "United Kingdom",
        destCode: "GB",
        annualVolumeTeus: "280,000",
        yoyGrowth: 12.1,
        tariffRate: "3.5%",
        tariffType: "Preferential",
        marketShare: 5.8,
        status: "Optimal",
        avgTransitDays: 22,
        legalTariffCode: "UK Global Tariff 6302.21 / UKVFTA Schedule",
        statutorySource: "General Statistics Office of Vietnam / HM Revenue & Customs",
        regulatoryAuthority: "UK HM Revenue & Customs (HMRC)",
        complianceNote: "Preferential ad-valorem duty rate tapering under UK-Vietnam Free Trade Agreement (UKVFTA) Art. 2.7.",
      },
      {
        id: "cor-6302-6",
        origin: "China",
        originCode: "CN",
        destination: "United States",
        destCode: "US",
        annualVolumeTeus: "890,000",
        yoyGrowth: -4.3,
        tariffRate: "19.5%",
        tariffType: "MFN",
        marketShare: 18.5,
        status: "Scrutiny",
        avgTransitDays: 16,
        legalTariffCode: "HTSUS 6302.31.5035 + Sec 301 List 4A",
        statutorySource: "U.S. CBP Automated Commercial Environment (ACE) / USITC DataWeb",
        regulatoryAuthority: "U.S. Customs & Border Protection (CBP) Regulatory Audit",
        complianceNote: "Subject to mandatory supply chain tracing under Uyghur Forced Labor Prevention Act (UFLPA) & Section 301 List 4A additional ad-valorem duty.",
      },
    ],
  },
  "8471": {
    code: "8471",
    name: "Automatic data processing machines & units",
    shortName: "Computing Machinery",
    category: "Machinery & Electronics",
    chapter: "Chapter 84: Nuclear reactors, boilers, machinery and mechanical appliances",
    totalAnnualTeus: "8.14M TEUs",
    totalAnnualValueUsd: "$342.0B",
    yoyGrowth: 16.7,
    leadExportingNation: "China (48.1%)",
    statutorySources: [
      "UN Comtrade Database (HS 2022 Revision)",
      "WTO Information Technology Agreement (ITA-1 & ITA-2)",
      "USITC DataWeb (HTSUS 8471)",
      "Eurostat Comext Trade Statistics",
      "Taiwan Directorate General of Customs (TAITRA)",
    ],
    nomenclatureRef: "WCO HS 2022 Heading 8471 / WTO ITA-1 Plurilateral Agreement",
    volumeTimeline: [
      { period: "Q1 '23", teus: 1720000, valueUsdMillions: 68800, yoyDelta: 7.1 },
      { period: "Q2 '23", teus: 1840000, valueUsdMillions: 73600, yoyDelta: 8.4 },
      { period: "Q3 '23", teus: 2010000, valueUsdMillions: 82400, yoyDelta: 11.2 },
      { period: "Q4 '23", teus: 1950000, valueUsdMillions: 80000, yoyDelta: 9.8 },
      { period: "Q1 '24", teus: 1890000, valueUsdMillions: 77500, yoyDelta: 9.9 },
      { period: "Q2 '24", teus: 2060000, valueUsdMillions: 84400, yoyDelta: 12.0 },
      { period: "Q3 '24", teus: 2290000, valueUsdMillions: 93800, yoyDelta: 13.9 },
      { period: "Q4 '24", teus: 2220000, valueUsdMillions: 91000, yoyDelta: 13.8 },
      { period: "Q1 '25", teus: 2150000, valueUsdMillions: 88100, yoyDelta: 13.8 },
      { period: "Q2 '25", teus: 2380000, valueUsdMillions: 97500, yoyDelta: 15.5 },
      { period: "Q3 '25", teus: 2640000, valueUsdMillions: 108200, yoyDelta: 15.3 },
      { period: "Q4 '25", teus: 2580000, valueUsdMillions: 105700, yoyDelta: 16.2 },
    ],
    topDestinations: [
      { country: "United States", code: "US", teus: 3120000, share: 38.3, growth: 18.2 },
      { country: "Netherlands", code: "NL", teus: 1450000, share: 17.8, growth: 14.5 },
      { country: "Japan", code: "JP", teus: 920000, share: 11.3, growth: 11.0 },
      { country: "Germany", code: "DE", teus: 790000, share: 9.7, growth: 8.9 },
      { country: "Singapore", code: "SG", teus: 610000, share: 7.5, growth: 22.4 },
    ],
    topCorridors: [
      {
        id: "cor-8471-1",
        origin: "Taiwan",
        originCode: "TW",
        destination: "United States",
        destCode: "US",
        annualVolumeTeus: "1,890,000",
        yoyGrowth: 24.6,
        tariffRate: "0.0%",
        tariffType: "FTA",
        marketShare: 23.2,
        status: "High Demand",
        avgTransitDays: 14,
        legalTariffCode: "HTSUS 8471.50.0150 (WTO ITA-1)",
        statutorySource: "UN Comtrade / USITC DataWeb (Schedule B & HTSUS 8471)",
        regulatoryAuthority: "U.S. Customs & Border Protection / DOC BIS",
        complianceNote: "Bound zero-tariff rate under WTO Information Technology Agreement (ITA-1). Subject to DOC BIS Export Administration Regulations (EAR99).",
      },
      {
        id: "cor-8471-2",
        origin: "Vietnam",
        originCode: "VN",
        destination: "United States",
        destCode: "US",
        annualVolumeTeus: "1,120,000",
        yoyGrowth: 31.2,
        tariffRate: "0.0%",
        tariffType: "MFN",
        marketShare: 13.8,
        status: "Optimal",
        avgTransitDays: 19,
        legalTariffCode: "HTSUS 8471.49.0000 (Col. 1 General)",
        statutorySource: "General Statistics Office of Vietnam / US Census Bureau",
        regulatoryAuthority: "U.S. Customs and Border Protection (CBP)",
        complianceNote: "Electronics assembly supply-chain diversification hub; unladed via Port of Long Beach & Port of Tacoma with full automated entry.",
      },
      {
        id: "cor-8471-3",
        origin: "China",
        originCode: "CN",
        destination: "Netherlands",
        destCode: "NL",
        annualVolumeTeus: "1,340,000",
        yoyGrowth: 6.8,
        tariffRate: "0.0%",
        tariffType: "MFN",
        marketShare: 16.5,
        status: "Optimal",
        avgTransitDays: 27,
        legalTariffCode: "EU TARIC 8471.50.00.00 (WTO ITA)",
        statutorySource: "Eurostat Comext / Port of Rotterdam Customs Directorate",
        regulatoryAuthority: "Dutch Customs Administration (Belastingdienst)",
        complianceNote: "Unladed via Rotterdam Maasvlakte terminals; bonded customs transit into pan-European distribution hubs at 0.0% statutory duty.",
      },
      {
        id: "cor-8471-4",
        origin: "India",
        originCode: "IN",
        destination: "United Arab Emirates",
        destCode: "AE",
        annualVolumeTeus: "310,000",
        yoyGrowth: 41.5,
        tariffRate: "0.0%",
        tariffType: "FTA",
        marketShare: 3.8,
        status: "High Demand",
        avgTransitDays: 4,
        legalTariffCode: "GCC Common Customs Tariff 8471.50 / CEPA",
        statutorySource: "India DGFT Trade Statistics / Dubai Customs JAFZA",
        regulatoryAuthority: "Dubai Customs & India Electronics Export Promotion Council (ESC)",
        complianceNote: "High-value air/sea freight through Jebel Ali Port with digital CEPA Rules of Origin certification.",
      },
      {
        id: "cor-8471-5",
        origin: "South Korea",
        originCode: "KR",
        destination: "Japan",
        destCode: "JP",
        annualVolumeTeus: "580,000",
        yoyGrowth: 8.9,
        tariffRate: "0.0%",
        tariffType: "FTA",
        marketShare: 7.1,
        status: "Optimal",
        avgTransitDays: 3,
        legalTariffCode: "Japan Customs Tariff 8471.50 (RCEP Schedule)",
        statutorySource: "Korea Customs Service (UNI-PASS) / Japan Customs (NACCS)",
        regulatoryAuthority: "Ministry of Finance Japan Customs Tariff Bureau",
        complianceNote: "Tariff-exempt entry under Regional Comprehensive Economic Partnership (RCEP) with electronic Form RCEP-1 verification.",
      },
    ],
  },
  "8517": {
    code: "8517",
    name: "Telephone sets, smartphones & transceivers",
    shortName: "Telecom & Smartphones",
    category: "Electrical Equipment",
    chapter: "Chapter 85: Electrical machinery and equipment; sound recorders and reproducers",
    totalAnnualTeus: "6.45M TEUs",
    totalAnnualValueUsd: "$298.1B",
    yoyGrowth: 14.1,
    leadExportingNation: "China & India",
    statutorySources: [
      "UN Comtrade Database (HS 2022 Revision)",
      "USITC DataWeb (HTSUS 8517)",
      "India Ministry of Commerce & Industry (DGFT PLI Telemetry)",
      "Eurostat Comext Trade Statistics",
      "WTO Integrated Tariff Database",
    ],
    nomenclatureRef: "WCO HS 2022 Heading 8517 / USITC HTSUS Chapter 85",
    volumeTimeline: [
      { period: "Q1 '23", teus: 1350000, valueUsdMillions: 62000, yoyDelta: 8.3 },
      { period: "Q2 '23", teus: 1420000, valueUsdMillions: 65300, yoyDelta: 7.9 },
      { period: "Q3 '23", teus: 1680000, valueUsdMillions: 77200, yoyDelta: 12.0 },
      { period: "Q4 '23", teus: 1740000, valueUsdMillions: 80000, yoyDelta: 13.1 },
      { period: "Q1 '24", teus: 1490000, valueUsdMillions: 68500, yoyDelta: 10.4 },
      { period: "Q2 '24", teus: 1580000, valueUsdMillions: 72700, yoyDelta: 11.3 },
      { period: "Q3 '24", teus: 1890000, valueUsdMillions: 86900, yoyDelta: 12.5 },
      { period: "Q4 '24", teus: 1980000, valueUsdMillions: 91100, yoyDelta: 13.8 },
      { period: "Q1 '25", teus: 1690000, valueUsdMillions: 77700, yoyDelta: 13.4 },
      { period: "Q2 '25", teus: 1810000, valueUsdMillions: 83300, yoyDelta: 14.6 },
      { period: "Q3 '25", teus: 2150000, valueUsdMillions: 98900, yoyDelta: 13.8 },
      { period: "Q4 '25", teus: 2260000, valueUsdMillions: 103900, yoyDelta: 14.1 },
    ],
    topDestinations: [
      { country: "United States", code: "US", teus: 2480000, share: 38.4, growth: 15.6 },
      { country: "United Arab Emirates", code: "AE", teus: 1040000, share: 16.1, growth: 21.0 },
      { country: "Hong Kong", code: "HK", teus: 880000, share: 13.6, growth: 7.8 },
      { country: "Germany", code: "DE", teus: 690000, share: 10.7, growth: 9.4 },
      { country: "United Kingdom", code: "GB", teus: 520000, share: 8.1, growth: 11.2 },
    ],
    topCorridors: [
      {
        id: "cor-8517-1",
        origin: "India",
        originCode: "IN",
        destination: "United States",
        destCode: "US",
        annualVolumeTeus: "980,000",
        yoyGrowth: 68.2,
        tariffRate: "0.0%",
        tariffType: "MFN",
        marketShare: 15.2,
        status: "High Demand",
        avgTransitDays: 21,
        legalTariffCode: "HTSUS 8517.13.0000 (WTO ITA-1)",
        statutorySource: "US Census Bureau Foreign Trade / India DGFT PLI Registry",
        regulatoryAuthority: "U.S. Customs and Border Protection / FCC",
        complianceNote: "Production-Linked Incentive (PLI) smartphone export surge; duty-free under WTO ITA-1. Requires FCC equipment authorization.",
      },
      {
        id: "cor-8517-2",
        origin: "India",
        originCode: "IN",
        destination: "United Arab Emirates",
        destCode: "AE",
        annualVolumeTeus: "620,000",
        yoyGrowth: 34.1,
        tariffRate: "0.0%",
        tariffType: "FTA",
        marketShare: 9.6,
        status: "Optimal",
        avgTransitDays: 4,
        legalTariffCode: "GCC Unified Tariff 8517.13 / CEPA",
        statutorySource: "UAE FCSA / DGFT India Electronic Statistics",
        regulatoryAuthority: "Telecommunications and Digital Government Regulatory Authority (TDRA UAE)",
        complianceNote: "Middle East redistribution corridor via Dubai CommerCity and JAFZA with zero-tariff CEPA preferences.",
      },
      {
        id: "cor-8517-3",
        origin: "Vietnam",
        originCode: "VN",
        destination: "United States",
        destCode: "US",
        annualVolumeTeus: "1,180,000",
        yoyGrowth: 18.5,
        tariffRate: "0.0%",
        tariffType: "MFN",
        marketShare: 18.3,
        status: "Optimal",
        avgTransitDays: 18,
        legalTariffCode: "HTSUS 8517.13.0000 (Col. 1 General)",
        statutorySource: "USITC DataWeb / Vietnam Customs General Department",
        regulatoryAuthority: "U.S. Customs and Border Protection (CBP)",
        complianceNote: "Primary global export corridor for smart mobile terminals; cleared through Long Beach and Newark at bound 0.0% MFN.",
      },
      {
        id: "cor-8517-4",
        origin: "China",
        originCode: "CN",
        destination: "Germany",
        destCode: "DE",
        annualVolumeTeus: "610,000",
        yoyGrowth: 4.2,
        tariffRate: "0.0%",
        tariffType: "MFN",
        marketShare: 9.5,
        status: "Optimal",
        avgTransitDays: 28,
        legalTariffCode: "EU TARIC 8517.13.00.00 (WTO ITA)",
        statutorySource: "Eurostat Comext / Destatis Trade Registry",
        regulatoryAuthority: "Federal Network Agency (Bundesnetzagentur) & German Zoll",
        complianceNote: "Duty-free under WTO Information Technology Agreement; requires CE mark and EU Radio Equipment Directive (RED) compliance.",
      },
    ],
  },
  "0901": {
    code: "0901",
    name: "Coffee, whether or not roasted or decaffeinated",
    shortName: "Coffee & Specialty Beans",
    category: "Agriculture & Foodstuffs",
    chapter: "Chapter 09: Coffee, tea, maté and spices",
    totalAnnualTeus: "2.94M TEUs",
    totalAnnualValueUsd: "$36.8B",
    yoyGrowth: 8.9,
    leadExportingNation: "Brazil (41.5%)",
    statutorySources: [
      "International Coffee Organization (ICO) Monthly Trade Telemetry",
      "UN Comtrade Database (HS 2022 Revision)",
      "USITC DataWeb (HTSUS 0901)",
      "Eurostat Comext Trade Statistics",
      "USDA Foreign Agricultural Service (FAS)",
    ],
    nomenclatureRef: "WCO HS 2022 Heading 0901 / ICO Statistical Framework",
    volumeTimeline: [
      { period: "Q1 '23", teus: 640000, valueUsdMillions: 8000, yoyDelta: 3.4 },
      { period: "Q2 '23", teus: 710000, valueUsdMillions: 8875, yoyDelta: 5.1 },
      { period: "Q3 '23", teus: 780000, valueUsdMillions: 9750, yoyDelta: 6.8 },
      { period: "Q4 '23", teus: 730000, valueUsdMillions: 9125, yoyDelta: 4.9 },
      { period: "Q1 '24", teus: 680000, valueUsdMillions: 8500, yoyDelta: 6.2 },
      { period: "Q2 '24", teus: 760000, valueUsdMillions: 9500, yoyDelta: 7.0 },
      { period: "Q3 '24", teus: 840000, valueUsdMillions: 10500, yoyDelta: 7.7 },
      { period: "Q4 '24", teus: 790000, valueUsdMillions: 9875, yoyDelta: 8.2 },
      { period: "Q1 '25", teus: 730000, valueUsdMillions: 9125, yoyDelta: 7.4 },
      { period: "Q2 '25", teus: 820000, valueUsdMillions: 10250, yoyDelta: 7.9 },
      { period: "Q3 '25", teus: 910000, valueUsdMillions: 11375, yoyDelta: 8.3 },
      { period: "Q4 '25", teus: 860000, valueUsdMillions: 10750, yoyDelta: 8.9 },
    ],
    topDestinations: [
      { country: "United States", code: "US", teus: 980000, share: 33.3, growth: 7.8 },
      { country: "Germany", code: "DE", teus: 640000, share: 21.8, growth: 6.1 },
      { country: "Italy", code: "IT", teus: 390000, share: 13.3, growth: 5.4 },
      { country: "Japan", code: "JP", teus: 280000, share: 9.5, growth: 12.0 },
      { country: "Belgium", code: "BE", teus: 220000, share: 7.5, growth: 8.2 },
    ],
    topCorridors: [
      {
        id: "cor-0901-1",
        origin: "Brazil",
        originCode: "BR",
        destination: "United States",
        destCode: "US",
        annualVolumeTeus: "740,000",
        yoyGrowth: 9.2,
        tariffRate: "0.0%",
        tariffType: "MFN",
        marketShare: 25.2,
        status: "Optimal",
        avgTransitDays: 14,
        legalTariffCode: "HTSUS 0901.11.0015 (Col. 1 General)",
        statutorySource: "International Coffee Organization (ICO) / USITC DataWeb",
        regulatoryAuthority: "U.S. FDA & USDA Animal and Plant Health Inspection Service (APHIS)",
        complianceNote: "Duty-free under Col. 1 General; requires FDA Prior Notice under Bioterrorism Act & USDA phytosanitary certificate.",
      },
      {
        id: "cor-0901-2",
        origin: "Colombia",
        originCode: "CO",
        destination: "United States",
        destCode: "US",
        annualVolumeTeus: "420,000",
        yoyGrowth: 6.5,
        tariffRate: "0.0%",
        tariffType: "FTA",
        marketShare: 14.3,
        status: "Optimal",
        avgTransitDays: 9,
        legalTariffCode: "US-Colombia TPA (HTSUS 0901.11.00)",
        statutorySource: "Federación Nacional de Cafeteros de Colombia / US Customs CBP",
        regulatoryAuthority: "U.S. Customs and Border Protection & USDA",
        complianceNote: "Tariff-free under U.S.-Colombia Trade Promotion Agreement Art. 2.3; accompanied by FNC quality seal & ICO Certificate of Origin.",
      },
      {
        id: "cor-0901-3",
        origin: "Vietnam",
        originCode: "VN",
        destination: "Germany",
        destCode: "DE",
        annualVolumeTeus: "390,000",
        yoyGrowth: 11.4,
        tariffRate: "0.0%",
        tariffType: "FTA",
        marketShare: 13.3,
        status: "Optimal",
        avgTransitDays: 24,
        legalTariffCode: "EU-Vietnam FTA (TARIC 0901.11.00.00)",
        statutorySource: "Eurostat Comext / Vietnam Coffee-Cocoa Association (Vicofa)",
        regulatoryAuthority: "European Commission DG AGRI & German Federal Office for Agriculture (BLE)",
        complianceNote: "Full tariff exemption under EVFTA; subject to EU Deforestation Regulation (EUDR) farm geolocation diligence.",
      },
      {
        id: "cor-0901-4",
        origin: "Ethiopia",
        originCode: "ET",
        destination: "Japan",
        destCode: "JP",
        annualVolumeTeus: "180,000",
        yoyGrowth: 15.8,
        tariffRate: "0.0%",
        tariffType: "Preferential",
        marketShare: 6.1,
        status: "High Demand",
        avgTransitDays: 22,
        legalTariffCode: "Japan Customs Tariff 0901.11 (LDC GSP Scheme)",
        statutorySource: "National Bank of Ethiopia / Japan Ministry of Finance",
        regulatoryAuthority: "Japan Customs & Ministry of Health, Labour and Welfare (MHLW)",
        complianceNote: "Duty-free under Japan's Generalized System of Preferences (GSP) for Least Developed Countries; pesticide residue testing verified.",
      },
    ],
  },
};

export const PRESET_HS_CODES = [
  { code: "6302", label: "6302 — Bed Linens", category: "Textiles" },
  { code: "8471", label: "8471 — Computing Machinery", category: "Electronics" },
  { code: "8517", label: "8517 — Telecom & Smartphones", category: "Hardware" },
  { code: "0901", label: "0901 — Coffee & Specialty", category: "Agri-Trade" },
];
